import '../models/tool_model.dart';
import '../models/user_model.dart';

class DummyData {
  // Categories with realistic real equipment photography
  static List<CategoryModel> categories = [
    CategoryModel(
      id: '1',
      name: 'Drilling Machines',
      icon: '🔧',
      imageUrl: 'assets/images/drilling_machine.png',
      toolCount: 45,
    ),
    CategoryModel(
      id: '2',
      name: 'Concrete Mixers',
      icon: '🏗️',
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      toolCount: 16,
    ),
    CategoryModel(
      id: '3',
      name: 'Welding Machines',
      icon: '⚡',
      imageUrl: 'assets/images/real_mig_welder.png',
      toolCount: 13,
    ),
    CategoryModel(
      id: '4',
      name: 'Generators',
      icon: '🔌',
      imageUrl: 'assets/images/real_generator.png',
      toolCount: 19,
    ),
    CategoryModel(
      id: '5',
      name: 'Ladders',
      icon: '🪜',
      imageUrl: 'assets/images/real_folding_ladder.png',
      toolCount: 54,
    ),
    CategoryModel(
      id: '6',
      name: 'Cutting & Planing Tools',
      icon: '✂️',
      imageUrl: 'assets/images/real_planer_jointer.png',
      toolCount: 67,
    ),
    CategoryModel(
      id: '7',
      name: 'Safety Equipment',
      icon: '⛑️',
      imageUrl: 'assets/images/real_safety_boots.png',
      toolCount: 89,
    ),
    CategoryModel(
      id: '8',
      name: 'Excavation Tools',
      icon: '🚜',
      imageUrl: 'assets/images/real_excavator.png',
      toolCount: 23,
    ),
  ];

  // Vendors
  static List<VendorModel> vendors = [
    VendorModel(
      id: 'v1',
      name: 'BuildRight Rentals',
      imageUrl: 'assets/images/vendor_logo.jpg',
      rating: 4.8,
      reviewCount: 234,
      location: 'T. Nagar',
      distance: 2.5,
    ),
    VendorModel(
      id: 'v2',
      name: 'Construction Pro',
      imageUrl: 'assets/images/vendor_logo.jpg',
      rating: 4.6,
      reviewCount: 189,
      location: 'Anna Nagar',
      distance: 4.2,
    ),
    VendorModel(
      id: 'v3',
      name: 'ToolMaster',
      imageUrl: 'assets/images/vendor_logo.jpg',
      rating: 4.9,
      reviewCount: 312,
      location: 'Velachery',
      distance: 1.8,
    ),
    VendorModel(
      id: 'v4',
      name: 'EquipRent',
      imageUrl: 'assets/images/vendor_logo.jpg',
      rating: 4.5,
      reviewCount: 156,
      location: 'Perambur',
      distance: 5.1,
    ),
  ];

  // Tools with photorealistic authentic equipment photography
  static List<ToolModel> tools = [
    // ─── Concrete Mixers (16 Items) ─────────────────────────────────────────────
    ToolModel(
      id: 'cm1',
      name: 'Electric cement mixer',
      category: 'Concrete Mixers',
      description: 'High-torque electric motor cement mixer for fast batching on residential & site builds.',
      pricePerDay: 4500.00,
      rating: 4.8,
      reviewCount: 112,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Power: 1.5HP Electric', 'Capacity: 180L', 'Speed: 28 RPM'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'cm2',
      name: 'Diesel concrete mixer',
      category: 'Concrete Mixers',
      description: 'Heavy-duty diesel engine powered mixer ideal for off-grid construction sites.',
      pricePerDay: 7500.00,
      rating: 4.9,
      reviewCount: 88,
      imageUrl: 'assets/images/concrete_mixer.png',
      imageUrls: ['assets/images/concrete_mixer.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Engine: 6HP Diesel', 'Drum Volume: 350L', 'Weight: 320kg'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'cm3',
      name: 'Mini concrete mixer',
      category: 'Concrete Mixers',
      description: 'Compact 63L mini portable electric cement mixer for small masonry jobs & DIY repairs.',
      pricePerDay: 2200.00,
      rating: 4.6,
      reviewCount: 64,
      imageUrl: 'assets/images/concrete_mixer_small.jpg',
      imageUrls: ['assets/images/concrete_mixer_small.jpg'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Capacity: 63 Liters', 'Motor: 220W', 'Portable Wheels'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'cm4',
      name: 'Tilting drum mixer',
      category: 'Concrete Mixers',
      description: 'Classic hand-wheel tilting drum mixer allowing smooth 360-degree concrete discharge.',
      pricePerDay: 5800.00,
      rating: 4.7,
      reviewCount: 79,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Drum Type: Tilting', 'Capacity: 200L', 'Discharge Angle: Adjustable'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'cm5',
      name: 'Reversible mixer',
      category: 'Concrete Mixers',
      description: 'Dual-action reversible drum mixer designed for rapid mixing in forward and discharge in reverse.',
      pricePerDay: 8200.00,
      rating: 4.8,
      reviewCount: 52,
      imageUrl: 'assets/images/concrete_mixer.png',
      imageUrls: ['assets/images/concrete_mixer.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Action: Reversible Drum', 'Motor: 7.5HP', 'Batch Time: 3 mins'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'cm6',
      name: 'Pan mixer',
      category: 'Concrete Mixers',
      description: 'Industrial heavy-duty concrete pan mixer with forced paddle blades for refractory materials.',
      pricePerDay: 9500.00,
      rating: 4.9,
      reviewCount: 41,
      imageUrl: 'assets/images/drum_mixer.jpg',
      imageUrls: ['assets/images/drum_mixer.jpg'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Pan Diameter: 1.2m', 'Capacity: 500kg', 'Power: 10HP'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'cm7',
      name: 'Handheld mixer',
      category: 'Concrete Mixers',
      description: 'Ergonomic dual-handle electric paddle mixer for mortar, grout, tile adhesive, and thinset.',
      pricePerDay: 1500.00,
      rating: 4.5,
      reviewCount: 130,
      imageUrl: 'assets/images/drilling_machine.png',
      imageUrls: ['assets/images/drilling_machine.png'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Power: 1600W', 'Variable Speed: 0-780 RPM', 'Dual Paddle'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'cm8',
      name: 'Batch mixer',
      category: 'Concrete Mixers',
      description: 'High capacity automated batching concrete mixer with digital weight sensor hopper.',
      pricePerDay: 12500.00,
      rating: 4.9,
      reviewCount: 35,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Batch Capacity: 750L', 'Hopper: Hydraulic Feed', 'Auto Timer'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'cm9',
      name: 'Drum mixer',
      category: 'Concrete Mixers',
      description: 'Standard heavy steel construction drum mixer with reinforced ring gear drive.',
      pricePerDay: 5200.00,
      rating: 4.7,
      reviewCount: 90,
      imageUrl: 'assets/images/drum_mixer.jpg',
      imageUrls: ['assets/images/drum_mixer.jpg'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Gear Drive: Cast Iron', 'Capacity: 250L', 'Motor: 3HP'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'cm10',
      name: 'Self loading mixer',
      category: 'Concrete Mixers',
      description: '4x4 self-loading mobile concrete mixer truck with front shovel bucket for high output.',
      pricePerDay: 35000.00,
      rating: 5.0,
      reviewCount: 22,
      imageUrl: 'assets/images/real_excavator.png',
      imageUrls: ['assets/images/real_excavator.png'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Output: 3.5 cu m/hr', 'Bucket: 600L Shovel', 'Drive: 4WD Diesel'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'cm11',
      name: 'Compulsor mixer',
      category: 'Concrete Mixers',
      description: 'Compulsor forced-action mortar mixer with high shear paddle rotation.',
      pricePerDay: 6800.00,
      rating: 4.8,
      reviewCount: 29,
      imageUrl: 'assets/images/concrete_mixer_small.jpg',
      imageUrls: ['assets/images/concrete_mixer_small.jpg'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Blades: 4 Rubber Scrapers', 'Power: 4HP', 'Capacity: 120L'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'cm12',
      name: 'Revolving drum mixer',
      category: 'Concrete Mixers',
      description: 'Continuous revolving drum mixer with smooth hydraulic discharge for bridge foundation work.',
      pricePerDay: 11000.00,
      rating: 4.7,
      reviewCount: 38,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Capacity: 500L', 'Engine: 10HP Diesel', 'Speed: 32 RPM'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'cm13',
      name: 'Continuous mixer',
      category: 'Concrete Mixers',
      description: 'Continuous volumetric concrete mixer for non-stop pouring projects.',
      pricePerDay: 18000.00,
      rating: 4.9,
      reviewCount: 19,
      imageUrl: 'assets/images/concrete_mixer.png',
      imageUrls: ['assets/images/concrete_mixer.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Pour Rate: 15 cu m/hr', 'Feeder: Screw Conveyor', 'Water Meter'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'cm14',
      name: 'Mobile drum mixer',
      category: 'Concrete Mixers',
      description: 'Towable mobile concrete drum mixer with pneumatic tires and road hitch.',
      pricePerDay: 7200.00,
      rating: 4.6,
      reviewCount: 47,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Towing Speed: Up to 50 km/h', 'Capacity: 300L', 'Diesel Motor'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'cm15',
      name: 'Twin shaft mixer',
      category: 'Concrete Mixers',
      description: 'Twin horizontal shaft concrete mixer for high-strength ready-mix concrete plants.',
      pricePerDay: 22000.00,
      rating: 5.0,
      reviewCount: 15,
      imageUrl: 'assets/images/drum_mixer.jpg',
      imageUrls: ['assets/images/drum_mixer.jpg'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Twin Shafts: Synchronized', 'Power: 30kW', 'Capacity: 1.0 cu m'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'cm16',
      name: 'Planetary mixer',
      category: 'Concrete Mixers',
      description: 'Planetary motion concrete mixer with counter-current mixing stars for precast concrete.',
      pricePerDay: 25000.00,
      rating: 4.9,
      reviewCount: 18,
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
      imageUrls: ['assets/images/real_electric_cement_mixer.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Star Blades: 3 Rotary Arm', 'Capacity: 750L', 'Motor: 25HP'],
      location: 'T. Nagar',
    ),

    // ─── Welding Machines (13 Items) ──────────────────────────────────────────
    ToolModel(
      id: 'wm1',
      name: 'Mig welder',
      category: 'Welding Machines',
      description: 'Professional MIG (GMAW) gas metal arc welder with auto wire feed unit.',
      pricePerDay: 5395.00,
      rating: 4.9,
      reviewCount: 156,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Current: 250A', 'Wire Diameter: 0.8-1.2mm', 'Voltage: 220V'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'wm2',
      name: 'Tig welder',
      category: 'Welding Machines',
      description: 'High precision AC/DC TIG pulse welder for aluminum, stainless steel, and pipe welding.',
      pricePerDay: 6200.00,
      rating: 4.9,
      reviewCount: 110,
      imageUrl: 'assets/images/welding_machine.png',
      imageUrls: ['assets/images/welding_machine.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['TIG Pulse: High Frequency', 'Current: 200A', 'Gas Shielded'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'wm3',
      name: 'Arc welder',
      category: 'Welding Machines',
      description: 'Heavy duty MMA inverter arc welding machine with anti-stick & hot start technology.',
      pricePerDay: 3500.00,
      rating: 4.7,
      reviewCount: 142,
      imageUrl: 'assets/images/welding_tool.jpg',
      imageUrls: ['assets/images/welding_tool.jpg'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Output: 400A', 'Electrode Size: 2.5-5.0mm', 'Inverter IGBT'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'wm4',
      name: 'Spot welder',
      category: 'Welding Machines',
      description: 'Pneumatic resistance spot welding machine for sheet metal fabrication.',
      pricePerDay: 7800.00,
      rating: 4.8,
      reviewCount: 45,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Power: 15kVA', 'Arm Reach: 500mm', 'Digital Timer'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'wm5',
      name: 'Stick welder',
      category: 'Welding Machines',
      description: 'Portable heavy duty stick electrode welder for rugged field structural steel work.',
      pricePerDay: 3200.00,
      rating: 4.6,
      reviewCount: 98,
      imageUrl: 'assets/images/welding_tool.jpg',
      imageUrls: ['assets/images/welding_tool.jpg'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Current: 300A', 'Duty Cycle: 60%', 'Weight: 8kg'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'wm6',
      name: 'Flux welder',
      category: 'Welding Machines',
      description: 'Gasless flux-cored arc welder for outdoor windy welding environments.',
      pricePerDay: 4200.00,
      rating: 4.7,
      reviewCount: 82,
      imageUrl: 'assets/images/welding_machine.png',
      imageUrls: ['assets/images/welding_machine.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Flux Core: 0.9mm', 'No Gas Required', 'Power: 180A'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'wm7',
      name: 'Oxy acetylene welder',
      category: 'Welding Machines',
      description: 'Complete oxy-acetylene gas welding, brazing & flame cutting torch rig kit.',
      pricePerDay: 4800.00,
      rating: 4.8,
      reviewCount: 67,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Twin Hose: 15m', 'Cutting Tip: #1, #2, #3', 'Dual Gauges'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'wm8',
      name: 'Ultra Sonic welder',
      category: 'Welding Machines',
      description: 'High frequency ultrasonic plastic & synthetic material bonding welder.',
      pricePerDay: 14500.00,
      rating: 4.9,
      reviewCount: 20,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Frequency: 20kHz', 'Power: 2000W', 'Digital Horn Generator'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'wm9',
      name: 'Induction welder',
      category: 'Welding Machines',
      description: 'High frequency electromagnetic induction pipe & tube seam welder.',
      pricePerDay: 18500.00,
      rating: 5.0,
      reviewCount: 14,
      imageUrl: 'assets/images/welding_tool.jpg',
      imageUrls: ['assets/images/welding_tool.jpg'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Power: 50kW', 'Heating Temp: Up to 1300°C', 'Auto Chiller'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'wm10',
      name: 'Seam welder',
      category: 'Welding Machines',
      description: 'Continuous rotary wheel seam welder for leak-proof tank and vessel welding.',
      pricePerDay: 16000.00,
      rating: 4.8,
      reviewCount: 18,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Wheel Diameter: 200mm', 'Welding Speed: 2.5 m/min', 'Power: 40kVA'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'wm11',
      name: 'Projection welder',
      category: 'Welding Machines',
      description: 'Heavy pneumatic projection resistance welder for stud and fastener attachment.',
      pricePerDay: 13500.00,
      rating: 4.7,
      reviewCount: 22,
      imageUrl: 'assets/images/welding_machine.png',
      imageUrls: ['assets/images/welding_machine.png'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Force: 12kN', 'Transformer: 75kVA', 'Microprocessor Control'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'wm12',
      name: 'Electron beam welder',
      category: 'Welding Machines',
      description: 'Vacuum chamber electron beam precision welder for aerospace alloy joining.',
      pricePerDay: 45000.00,
      rating: 5.0,
      reviewCount: 9,
      imageUrl: 'assets/images/real_mig_welder.png',
      imageUrls: ['assets/images/real_mig_welder.png'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Beam Power: 15kW', 'Vacuum Level: 10-4 mbar', 'CNC Axis'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'wm13',
      name: 'Friction welder',
      category: 'Welding Machines',
      description: 'Solid-state rotary friction welding machine for dissimilar metal joining.',
      pricePerDay: 28000.00,
      rating: 4.9,
      reviewCount: 12,
      imageUrl: 'assets/images/welding_tool.jpg',
      imageUrls: ['assets/images/welding_tool.jpg'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Spindle Speed: 3000 RPM', 'Forging Force: 150kN', 'Auto Chuck'],
      location: 'T. Nagar',
    ),

    // ─── Generators (Photorealistic Equipment Photography) ────────────────────
    ToolModel(
      id: 'gen1',
      name: 'Diesel Generator 5kW',
      category: 'Generators',
      description: 'Reliable diesel generator providing 5kW continuous power. Silent canopy included.',
      pricePerDay: 9960.00,
      rating: 4.6,
      reviewCount: 78,
      imageUrl: 'assets/images/real_generator.png',
      imageUrls: ['assets/images/real_generator.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Power: 5kW', 'Fuel: Diesel', 'Tank: 15L', 'Runtime: 8 hours'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'gen2',
      name: 'Silent Diesel Generator 10kVA',
      category: 'Generators',
      description: 'Acoustic soundproof 10kVA diesel generator for commercial sites & events.',
      pricePerDay: 15500.00,
      rating: 4.9,
      reviewCount: 94,
      imageUrl: 'assets/images/generator.png',
      imageUrls: ['assets/images/generator.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Output: 10kVA', 'Noise: <65dB', 'Auto Transfer Switch'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'gen3',
      name: 'Heavy Duty Industrial Generator 50kVA',
      category: 'Generators',
      description: 'Commercial 50kVA Cummins powered heavy industrial generator set.',
      pricePerDay: 32000.00,
      rating: 5.0,
      reviewCount: 31,
      imageUrl: 'assets/images/generator_tool.jpg',
      imageUrls: ['assets/images/generator_tool.jpg'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Engine: Cummins 4-Cylinder', 'Output: 50kVA 3-Phase', 'Fuel Tank: 120L'],
      location: 'Perambur',
    ),

    // ─── Excavation Tools (Photorealistic CAT Excavator Photography) ──────────
    ToolModel(
      id: 'ex1',
      name: 'Mini Excavator',
      category: 'Excavation Tools',
      description: 'Compact mini excavator perfect for small construction sites, landscaping, and utility work.',
      pricePerDay: 29050.00,
      rating: 4.9,
      reviewCount: 45,
      imageUrl: 'assets/images/real_excavator.png',
      imageUrls: ['assets/images/real_excavator.png'],
      isAvailable: true,
      vendor: vendors[0],
      specifications: ['Weight: 1.5 tons', 'Dig Depth: 8ft', 'Bucket: 0.04 cu yd'],
      location: 'T. Nagar',
    ),
    ToolModel(
      id: 'ex2',
      name: 'Heavy Crawler Excavator',
      category: 'Excavation Tools',
      description: '20-Ton crawler track excavator for deep foundation digging & site demolition.',
      pricePerDay: 48000.00,
      rating: 5.0,
      reviewCount: 28,
      imageUrl: 'assets/images/excavator.jpg',
      imageUrls: ['assets/images/excavator.jpg'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Weight: 20 Tons', 'Max Dig Reach: 30ft', 'Bucket: 1.0 cu yd'],
      location: 'Anna Nagar',
    ),
    ToolModel(
      id: 'ex3',
      name: 'Backhoe Loader Digger',
      category: 'Excavation Tools',
      description: 'JCB Backhoe Loader with front loader shovel and rear excavation arm.',
      pricePerDay: 38000.00,
      rating: 4.8,
      reviewCount: 62,
      imageUrl: 'assets/images/excavator_tool.jpg',
      imageUrls: ['assets/images/excavator_tool.jpg'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Engine: 76HP Turbo', 'Front Loader: 1.1 cu m', 'Dig Depth: 14ft'],
      location: 'Velachery',
    ),

    // ─── Ladders, Planers & Safety Boots (Photorealistic Genuine Photography) ─
    ToolModel(
      id: 'lad1',
      name: 'Folding ladders and articulate ladder',
      category: 'Ladders',
      description: 'Multi-position 16-in-1 heavy duty aluminum folding & articulated ladder with locking hinges.',
      pricePerDay: 2400.00,
      rating: 4.8,
      reviewCount: 115,
      imageUrl: 'assets/images/real_folding_ladder.png',
      imageUrls: ['assets/images/real_folding_ladder.png'],
      isAvailable: true,
      vendor: vendors[3],
      specifications: ['Max Height: 16ft', 'Positions: 16 Configurations', 'Capacity: 150kg'],
      location: 'Perambur',
    ),
    ToolModel(
      id: 'pl1',
      name: 'Planer and jointer',
      category: 'Cutting & Planing Tools',
      description: 'Benchtop woodworking planer and jointer combo for smooth timber surface finishing.',
      pricePerDay: 3600.00,
      rating: 4.7,
      reviewCount: 84,
      imageUrl: 'assets/images/real_planer_jointer.png',
      imageUrls: ['assets/images/real_planer_jointer.png'],
      isAvailable: true,
      vendor: vendors[2],
      specifications: ['Width: 10 inches', 'Motor: 1800W', 'Cutterhead Speed: 9000 RPM'],
      location: 'Velachery',
    ),
    ToolModel(
      id: 'sf1',
      name: 'Safety boots',
      category: 'Safety Equipment',
      description: 'Steel-toe puncture resistant waterproof leather safety work boots (ANSI certified).',
      pricePerDay: 950.00,
      rating: 4.9,
      reviewCount: 210,
      imageUrl: 'assets/images/real_safety_boots.png',
      imageUrls: ['assets/images/real_safety_boots.png'],
      isAvailable: true,
      vendor: vendors[1],
      specifications: ['Steel Toe Cap', 'Sole: Anti-Skid Rubber', 'Oil Resistant', 'Waterproof'],
      location: 'Anna Nagar',
    ),
  ];

  // Reviews
  static List<ReviewModel> reviews = [
    ReviewModel(
      id: 'r1',
      userName: 'John Smith',
      userImageUrl: 'assets/images/avatar.jpg',
      rating: 5.0,
      comment: 'Excellent tool! Worked perfectly for my project. Will definitely rent again.',
      date: DateTime(2024, 1, 15),
    ),
    ReviewModel(
      id: 'r2',
      userName: 'Sarah Johnson',
      userImageUrl: 'assets/images/avatar.jpg',
      rating: 4.5,
      comment: 'Good condition and easy to use. Delivery was on time.',
      date: DateTime(2024, 1, 10),
    ),
  ];

  // Notifications
  static List<NotificationModel> notifications = [
    NotificationModel(
      id: 'n1',
      title: 'Booking Accepted 🎉',
      message: 'Your booking for Electric cement mixer has been accepted by the shop owner.',
      type: 'booking',
      targetRole: 'customer',
      dateTime: DateTime.now().subtract(const Duration(hours: 2)),
      isRead: false,
    ),
  ];

  // User
  static UserModel currentUser = UserModel(
    id: 'u1',
    name: 'Alex Thompson',
    email: 'alex.thompson@email.com',
    phone: '+1 234 567 8900',
    imageUrl: 'assets/images/avatar.jpg',
    location: 'Chennai, Tamil Nadu',
  );

  // Bookings
  static List<BookingModel> bookings = [
    BookingModel(
      id: 'b1',
      tool: tools[0],
      startDate: DateTime(2024, 1, 25),
      endDate: DateTime(2024, 1, 28),
      totalPrice: 11205.00,
      status: 'active',
      createdAt: DateTime(2024, 1, 20),
    ),
  ];

  // Onboarding data
  static List<OnboardingData> onboardingData = [
    OnboardingData(
      title: 'Rent Smart',
      description: 'Find the perfect construction tools for your project at affordable prices.',
      imageUrl: 'assets/images/drilling_machine.png',
    ),
    OnboardingData(
      title: 'Build Faster',
      description: 'Get equipment delivered to your site and focus on what matters most.',
      imageUrl: 'assets/images/real_electric_cement_mixer.png',
    ),
    OnboardingData(
      title: 'Save Money',
      description: 'No need to buy expensive tools. Rent only when you need them.',
      imageUrl: 'assets/images/real_generator.png',
    ),
  ];
}

class OnboardingData {
  final String title;
  final String description;
  final String imageUrl;

  OnboardingData({
    required this.title,
    required this.description,
    required this.imageUrl,
  });
}
