// File generated by FlutterFire CLI & updated for toolsrental.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO_CLkWqGrY4CJOIAuFO_zvLGwQBtZVCc',
    appId: '1:561262627960:web:4da97b9f857affd19af18d',
    messagingSenderId: '561262627960',
    projectId: 'toolsrental',
    authDomain: 'toolsrental.firebaseapp.com',
    storageBucket: 'toolsrental.firebasestorage.app',
    measurementId: 'G-GCYYX56K9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDghQpKsxXSNvCKUJWfUi34JjfF6S40tBc',
    appId: '1:487528005514:android:b20034ed94a9accba35273',
    messagingSenderId: '487528005514',
    projectId: 'tools-bd286',
    storageBucket: 'tools-bd286.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_CLkWqGrY4CJOIAuFO_zvLGwQBtZVCc',
    appId: '1:561262627960:ios:8a26d73d7a615a5da35273',
    messagingSenderId: '561262627960',
    projectId: 'toolsrental',
    storageBucket: 'toolsrental.firebasestorage.app',
    iosBundleId: 'com.example.constructhub',
  );
}
