import 'package:flutter/material.dart';
import '../themes/app_theme.dart';
import '../models/tool_model.dart';
import '../widgets/app_image.dart';
import 'booking_screen.dart';

class CategoriesScreen extends StatefulWidget {
  const CategoriesScreen({super.key});

  @override
  State<CategoriesScreen> createState() => _CategoriesScreenState();
}

class _CategoriesScreenState extends State<CategoriesScreen> {
  int _selectedCategory = 0;

  final List<Map<String, dynamic>> _categories = [
    {'name': 'Drilling Machines', 'icon': Icons.hardware, 'image': 'assets/images/drilling_machine.png'},
    {'name': 'Concrete Mixers', 'icon': Icons.settings, 'image': 'assets/images/concrete_mixer.png'},
    {'name': 'Welding Machines', 'icon': Icons.bolt, 'image': 'assets/images/welding_machine.png'},
    {'name': 'Generators', 'icon': Icons.electrical_services, 'image': 'assets/images/generator.png'},
    {'name': 'Ladders', 'icon': Icons.stairs, 'image': 'assets/images/ladder.png'},
    {'name': 'Cutting Tools', 'icon': Icons.content_cut, 'image': 'assets/images/cutting_tool.png'},
    {'name': 'Safety Equipment', 'icon': Icons.security, 'image': 'assets/images/safety_equipment.jpg'},
    {'name': 'Excavation Tools', 'icon': Icons.agriculture, 'image': 'assets/images/excavator.jpg'},
  ];



  final List<Map<String, dynamic>> _tools = [
    // ── Drilling Machines ──
    {
      'category': 'Drilling Machines',
      'name': 'Bosch Rotary Hammer Drill',
      'price': 835,
      'rating': 4.7,
      'reviews': 128,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Makita Cordless Drill',
      'price': 665,
      'rating': 4.5,
      'reviews': 89,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/drill_tool.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'DeWalt Impact Driver',
      'price': 745,
      'rating': 4.6,
      'reviews': 156,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/drill_closeup.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Stanley Hammer Drill',
      'price': 575,
      'rating': 4.4,
      'reviews': 67,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Hitachi Rotary Drill',
      'price': 915,
      'rating': 4.8,
      'reviews': 142,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/drill_tool.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Black+Decker Cordless Drill',
      'price': 495,
      'rating': 4.3,
      'reviews': 78,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/drill_closeup.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Milwaukee Hammer Drill',
      'price': 1085,
      'rating': 4.9,
      'reviews': 198,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Ryobi Impact Driver',
      'price': 585,
      'rating': 4.5,
      'reviews': 92,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/drill_tool.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Craftsman Drill',
      'price': 625,
      'rating': 4.4,
      'reviews': 56,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/drill_closeup.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Porter Cable Drill',
      'price': 715,
      'rating': 4.6,
      'reviews': 134,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Festool Cordless Drill',
      'price': 1245,
      'rating': 4.8,
      'reviews': 167,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/drill_tool.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Metabo Hammer Drill',
      'price': 895,
      'rating': 4.7,
      'reviews': 145,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/drill_closeup.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Hilti Rotary Hammer',
      'price': 1455,
      'rating': 4.9,
      'reviews': 212,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Panasonic Cordless Drill',
      'price': 675,
      'rating': 4.5,
      'reviews': 83,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/drill_tool.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Skil Power Drill',
      'price': 425,
      'rating': 4.3,
      'reviews': 61,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/drill_closeup.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'AEG Hammer Drill',
      'price': 955,
      'rating': 4.6,
      'reviews': 118,
      'location': 'Porur, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },

    // ── Concrete Mixers ──
    {
      'category': 'Concrete Mixers',
      'name': 'Electric cement mixer',
      'price': 4500,
      'rating': 4.8,
      'reviews': 112,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/real_electric_cement_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Diesel concrete mixer',
      'price': 7500,
      'rating': 4.9,
      'reviews': 88,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/real_diesel_concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Mini concrete mixer',
      'price': 2200,
      'rating': 4.6,
      'reviews': 64,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/real_mini_concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Tilting drum mixer',
      'price': 5800,
      'rating': 4.7,
      'reviews': 79,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/real_electric_cement_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Reversible mixer',
      'price': 8200,
      'rating': 4.8,
      'reviews': 112,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Pan mixer',
      'price': 9500,
      'rating': 4.9,
      'reviews': 41,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/drum_mixer.jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Handheld mixer',
      'price': 1500,
      'rating': 4.5,
      'reviews': 130,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/drilling_machine.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Batch mixer',
      'price': 12500,
      'rating': 4.9,
      'reviews': 134,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/real_electric_cement_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Drum mixer',
      'price': 5200,
      'rating': 4.7,
      'reviews': 90,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/drum_mixer.jpg',
      'available': false,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Self loading mixer',
      'price': 35000,
      'rating': 5.0,
      'reviews': 22,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/real_excavator.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Compulsor mixer',
      'price': 6800,
      'rating': 4.8,
      'reviews': 29,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/real_mini_concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Revolving drum mixer',
      'price': 11000,
      'rating': 4.7,
      'reviews': 38,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/real_electric_cement_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Continuous mixer',
      'price': 18000,
      'rating': 4.9,
      'reviews': 98,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Mobile drum mixer',
      'price': 7200,
      'rating': 4.6,
      'reviews': 47,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/real_diesel_concrete_mixer.png',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Twin shaft mixer',
      'price': 22000,
      'rating': 5.0,
      'reviews': 15,
      'location': 'Porur, Chennai',
      'image': 'assets/images/drum_mixer.jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Planetary mixer',
      'price': 25000,
      'rating': 4.9,
      'reviews': 18,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/real_electric_cement_mixer.png',
      'available': true,
    },


    // ── Welding Machines ──
    {
      'category': 'Welding Machines',
      'name': 'Mig welder',
      'price': 5395,
      'rating': 4.9,
      'reviews': 156,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Tig welder',
      'price': 6200,
      'rating': 4.9,
      'reviews': 110,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/welding_machine.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Arc welder',
      'price': 3500,
      'rating': 4.7,
      'reviews': 142,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/welding_tool.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Spot welder',
      'price': 7800,
      'rating': 4.8,
      'reviews': 45,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': false,
    },
    {
      'category': 'Welding Machines',
      'name': 'Stick welder',
      'price': 3200,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/welding_tool.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Flux welder',
      'price': 4200,
      'rating': 4.7,
      'reviews': 82,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/welding_machine.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Oxy acetylene welder',
      'price': 4800,
      'rating': 4.8,
      'reviews': 67,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Ultra Sonic welder',
      'price': 14500,
      'rating': 4.9,
      'reviews': 20,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Induction welder',
      'price': 18500,
      'rating': 5.0,
      'reviews': 14,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/welding_tool.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Seam welder',
      'price': 16000,
      'rating': 4.8,
      'reviews': 18,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Projection welder',
      'price': 13500,
      'rating': 4.7,
      'reviews': 22,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/welding_machine.png',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Electron beam welder',
      'price': 45000,
      'rating': 5.0,
      'reviews': 9,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/real_mig_welder.png',
      'available': false,
    },
    {
      'category': 'Welding Machines',
      'name': 'Friction welder',
      'price': 28000,
      'rating': 4.9,
      'reviews': 12,
      'location': 'Porur, Chennai',
      'image': 'assets/images/welding_tool.jpg',
      'available': true,
    },

    // ── Generators ──
    {
      'category': 'Generators',
      'name': 'Diesel Generator 5kW',
      'price': 9960,
      'rating': 4.6,
      'reviews': 78,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/real_generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Silent Diesel Generator 10kVA',
      'price': 15500,
      'rating': 4.9,
      'reviews': 94,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Heavy Duty Industrial Generator 50kVA',
      'price': 32000,
      'rating': 5.0,
      'reviews': 31,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },

    {
      'category': 'Generators',
      'name': 'Portable Power Generator',
      'price': 4575,
      'rating': 4.7,
      'reviews': 98,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Diesel Generator',
      'price': 8665,
      'rating': 4.6,
      'reviews': 78,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Gas Generator',
      'price': 5365,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Solar Generator',
      'price': 12450,
      'rating': 4.8,
      'reviews': 134,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Inverter Generator',
      'price': 7455,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Standby Generator',
      'price': 16550,
      'rating': 4.9,
      'reviews': 67,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Prime Power Generator',
      'price': 20750,
      'rating': 4.6,
      'reviews': 45,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Silent Generator',
      'price': 9125,
      'rating': 4.7,
      'reviews': 112,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Hybrid Generator',
      'price': 14550,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Bi-Fuel Generator',
      'price': 11250,
      'rating': 4.6,
      'reviews': 78,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Natural Gas Generator',
      'price': 8665,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Propane Generator',
      'price': 7875,
      'rating': 4.7,
      'reviews': 92,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/generator.png',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Wind Generator',
      'price': 24750,
      'rating': 4.8,
      'reviews': 34,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Hydro Generator',
      'price': 33250,
      'rating': 4.6,
      'reviews': 23,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/generator.png',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Marine Generator',
      'price': 18650,
      'rating': 4.5,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/generator_tool.jpg',
      'available': true,
    },

    // ── Ladders ──
    {
      'category': 'Ladders',
      'name': 'Aluminum Extension Ladder',
      'price': 1245,
      'rating': 4.6,
      'reviews': 112,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Fiberglass Step Ladder',
      'price': 905,
      'rating': 4.5,
      'reviews': 87,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/fiberglass_step_ladder.jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Telescoping Ladder',
      'price': 1455,
      'rating': 4.7,
      'reviews': 134,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Platform Ladder',
      'price': 1655,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/platform_ladder.jpg',
      'available': false,
    },
    {
      'category': 'Ladders',
      'name': 'Attic Ladder',
      'price': 1865,
      'rating': 4.5,
      'reviews': 67,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Rolling Ladder',
      'price': 2245,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/rolling_ladder.jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Step Stool',
      'price': 495,
      'rating': 4.4,
      'reviews': 145,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Scaffold Ladder',
      'price': 2875,
      'rating': 4.8,
      'reviews': 56,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/scaffold_ladder.jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Multi-Purpose Ladder',
      'price': 2075,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Orchard Ladder',
      'price': 1245,
      'rating': 4.5,
      'reviews': 78,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/orchard_ladder.jpg',
      'available': false,
    },
    {
      'category': 'Ladders',
      'name': 'Fire Escape Ladder',
      'price': 1655,
      'rating': 4.7,
      'reviews': 92,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Pool Ladder',
      'price': 1455,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/pool_ladder.jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Library Ladder',
      'price': 1865,
      'rating': 4.6,
      'reviews': 45,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Folding Ladder',
      'price': 835,
      'rating': 4.5,
      'reviews': 134,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/folding_ladder.jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Straight Ladder',
      'price': 745,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/ladder.png',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Articulated Ladder',
      'price': 2075,
      'rating': 4.6,
      'reviews': 67,
      'location': 'Porur, Chennai',
      'image': 'assets/images/articulated_ladder.jpg',
      'available': false,
    },

    // ── Cutting Tools ──
    {
      'category': 'Cutting Tools',
      'name': 'Angle Grinder',
      'price': 2075,
      'rating': 4.7,
      'reviews': 145,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/angle_grinder.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Circular Saw',
      'price': 2475,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/cutting_tool.png',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Jigsaw',
      'price': 1655,
      'rating': 4.5,
      'reviews': 78,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/jigsaw.jpg',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Reciprocating Saw',
      'price': 1865,
      'rating': 4.7,
      'reviews': 112,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/angle_grinder.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Table Saw',
      'price': 3345,
      'rating': 4.8,
      'reviews': 134,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/cutting_tool.png',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Miter Saw',
      'price': 2875,
      'rating': 4.6,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/miter_saw.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Band Saw',
      'price': 4155,
      'rating': 4.7,
      'reviews': 67,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/band_saw.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Chop Saw',
      'price': 2245,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/cutting_tool.png',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Tile Saw',
      'price': 1655,
      'rating': 4.6,
      'reviews': 92,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/tile_saw.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Scroll Saw',
      'price': 2075,
      'rating': 4.7,
      'reviews': 78,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/angle_grinder.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Rotary Tool',
      'price': 835,
      'rating': 4.4,
      'reviews': 145,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/cutting_tool.png',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Oscillating Tool',
      'price': 1245,
      'rating': 4.5,
      'reviews': 112,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/oscillating_tool.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Router',
      'price': 1455,
      'rating': 4.6,
      'reviews': 89,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/router.jpg',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Planer and jointer',
      'price': 3600,
      'rating': 4.7,
      'reviews': 84,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/real_planer_jointer.png',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Planer',
      'price': 1865,
      'rating': 4.7,
      'reviews': 67,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/planer.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Jointer',
      'price': 2245,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/jointer.jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Thickness Planer',
      'price': 2875,
      'rating': 4.8,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/thickness_planer.jpg',
      'available': true,
    },

    // ── Safety Equipment ──
    {
      'category': 'Safety Equipment',
      'name': 'Safety Helmet Set',
      'price': 415,
      'rating': 4.8,
      'reviews': 234,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/safety_helmet_set.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Goggles',
      'price': 250,
      'rating': 4.5,
      'reviews': 167,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/safety_goggles.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Gloves',
      'price': 165,
      'rating': 4.6,
      'reviews': 189,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/safety_gloves.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Boots',
      'price': 950,
      'rating': 4.9,
      'reviews': 210,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/real_safety_boots.png',
      'available': true,
    },

    {
      'category': 'Safety Equipment',
      'name': 'Safety Vest',
      'price': 295,
      'rating': 4.5,
      'reviews': 198,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/safety_vest.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Ear Protection',
      'price': 185,
      'rating': 4.4,
      'reviews': 134,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/ear_protection.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Face Shield',
      'price': 225,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/face_shield.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Respirator Mask',
      'price': 345,
      'rating': 4.7,
      'reviews': 167,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/respirator_mask.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Harness',
      'price': 1245,
      'rating': 4.8,
      'reviews': 89,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/safety_harness.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Knee Pads',
      'price': 275,
      'rating': 4.5,
      'reviews': 145,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/knee_pads.jpg',
      'available': false,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Glasses',
      'price': 195,
      'rating': 4.6,
      'reviews': 178,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/safety_glasses.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Hard Hat',
      'price': 375,
      'rating': 4.7,
      'reviews': 156,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/hard_hat.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'High Visibility Jacket',
      'price': 425,
      'rating': 4.5,
      'reviews': 134,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/high_vis_jacket.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Steel Toe Shoes',
      'price': 955,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/steel_toe_shoes.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Dust Mask',
      'price': 85,
      'rating': 4.4,
      'reviews': 198,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/dust_mask.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Welding Helmet',
      'price': 865,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Porur, Chennai',
      'image': 'assets/images/welding_helmet.jpg',
      'available': false,
    },

    // ── Excavation Tools ──
    {
      'category': 'Excavation Tools',
      'name': 'Mini Excavator',
      'price': 29050,
      'rating': 4.9,
      'reviews': 45,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/real_excavator.png',
      'available': true,
    },

    {
      'category': 'Excavation Tools',
      'name': 'Backhoe Loader',
      'price': 35000,
      'rating': 4.8,
      'reviews': 32,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/excavator_tool.jpg',
      'available': true,
    },
    {
      'category': 'Excavation Tools',
      'name': 'Trench Digger',
      'price': 5400,
      'rating': 4.6,
      'reviews': 19,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/excavator.jpg',
      'available': true,
    },
    {
      'category': 'Excavation Tools',
      'name': 'Skid Steer Loader',
      'price': 8500,
      'rating': 4.7,
      'reviews': 28,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/excavator_tool.jpg',
      'available': false,
    },
  ];

  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';

  List<Map<String, dynamic>> get _filteredTools {
    final categoryName = _categories[_selectedCategory]['name'];
    return _tools.where((tool) {
      final matchesCategory = tool['category'] == categoryName;
      final matchesSearch = _searchQuery.isEmpty ||
          tool['name'].toString().toLowerCase().contains(_searchQuery.toLowerCase()) ||
          tool['category'].toString().toLowerCase().contains(_searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    }).toList();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF141414),
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 12),
            // Search Bar
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: TextField(
                controller: _searchController,
                onChanged: (val) => setState(() => _searchQuery = val),
                style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Colors.white),
                decoration: InputDecoration(
                  hintText: 'Search equipment (e.g. Electric cement mixer, MIG welder)...',
                  hintStyle: const TextStyle(fontSize: 12, color: AppTheme.mediumGray),
                  prefixIcon: const Icon(Icons.search, color: AppTheme.primaryYellow),
                  suffixIcon: _searchQuery.isNotEmpty
                      ? IconButton(
                          icon: const Icon(Icons.clear, size: 18, color: Colors.white70),
                          onPressed: () => setState(() {
                            _searchController.clear();
                            _searchQuery = '';
                          }),
                        )
                      : null,
                  fillColor: const Color(0xFF1E1E1E),
                  filled: true,
                  contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: BorderSide.none,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 14),

            // Category tabs
            SizedBox(
              height: 96,
              child: ListView.builder(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                scrollDirection: Axis.horizontal,
                itemCount: _categories.length,
                itemBuilder: (context, i) {
                  final selected = i == _selectedCategory;
                  return GestureDetector(
                    onTap: () => setState(() => _selectedCategory = i),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      width: 88,
                      margin: const EdgeInsets.symmetric(horizontal: 4),
                      decoration: BoxDecoration(
                        color: selected
                            ? AppTheme.primaryYellow.withOpacity(0.15)
                            : const Color(0xFF1E1E1E),
                        borderRadius: BorderRadius.circular(14),
                        border: Border.all(
                          color: selected
                              ? AppTheme.primaryYellow
                              : Colors.white12,
                          width: selected ? 1.8 : 1,
                        ),
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.circular(10),
                            child: SizedBox(
                              width: 36,
                              height: 36,
                              child: AppImage(
                                imageUrl: _categories[i]['image'] as String,
                                fit: BoxFit.cover,
                                errorWidget: Icon(
                                  _categories[i]['icon'] as IconData,
                                  color: selected
                                      ? AppTheme.primaryYellow
                                      : AppTheme.mediumGray,
                                  size: 24,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(height: 6),
                          Text(
                            _categories[i]['name'] as String,
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: selected
                                  ? AppTheme.primaryYellow
                                  : Colors.white70,
                              fontSize: 10,
                              fontWeight: selected
                                  ? FontWeight.bold
                                  : FontWeight.normal,
                            ),
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
            const SizedBox(height: 16),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    '${_filteredTools.length} Premium Tools Available',
                    style: const TextStyle(color: Colors.white70, fontSize: 13, fontWeight: FontWeight.bold),
                  ),
                  Text(
                    _categories[_selectedCategory]['name'] as String,
                    style: const TextStyle(color: AppTheme.primaryYellow, fontSize: 12, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 10),

            // Tools Grid
            Expanded(
              child: GridView.builder(
                padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  crossAxisSpacing: 12,
                  mainAxisSpacing: 14,
                  childAspectRatio: 0.53,
                ),
                itemCount: _filteredTools.length,
                itemBuilder: (context, i) {
                  final tool = _filteredTools[i];
                  return _buildToolCard(tool);
                },
              ),
            ),
          ],
        ),
      ),
    );
  }


  Widget _buildToolCard(Map<String, dynamic> tool) {
    return GestureDetector(
      onTap: () => _navigateToBooking(tool),
      child: Container(
        decoration: BoxDecoration(
          color: const Color(0xFF1E1E1E),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: AppTheme.primaryYellow.withOpacity(0.2)),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.3),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Image + badges
            Stack(
              children: [
                ClipRRect(
                  borderRadius: const BorderRadius.vertical(
                    top: Radius.circular(16),
                  ),
                  child: AspectRatio(
                    aspectRatio: 1.25,
                    child: AppImage(
                      imageUrl: tool['image'] as String,
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
                if (!(tool['available'] as bool))
                  Positioned(
                    top: 8,
                    left: 8,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),
                      decoration: BoxDecoration(
                        color: AppTheme.accentRed,
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: const Text(
                        'Rented Out',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 9,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                Positioned(
                  top: 8,
                  right: 8,
                  child: Container(
                    width: 28,
                    height: 28,
                    decoration: const BoxDecoration(
                      color: Colors.black54,
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.favorite_border,
                      color: AppTheme.primaryYellow,
                      size: 15,
                    ),
                  ),
                ),
              ],
            ),

            // Card Text Details
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(10),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      tool['name'] as String,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 13,
                        fontWeight: FontWeight.bold,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 3),
                    Row(
                      children: [
                        const Icon(Icons.star_rounded, color: AppTheme.primaryYellow, size: 13),
                        const SizedBox(width: 3),
                        Text(
                          '${tool['rating']} (${tool['reviews']})',
                          style: const TextStyle(color: Colors.white60, fontSize: 10),
                        ),
                        const Spacer(),
                        const Icon(Icons.location_on_outlined, color: AppTheme.mediumGray, size: 10),
                        Expanded(
                          child: Text(
                            tool['location'] as String,
                            style: const TextStyle(color: AppTheme.mediumGray, fontSize: 9),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 6),
                    Text(
                      'High-performance ${tool['category']} ready for rental with site delivery compliance.',
                      style: const TextStyle(color: Colors.white54, fontSize: 10, height: 1.2),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const Spacer(),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text('Rate:', style: TextStyle(color: AppTheme.mediumGray, fontSize: 10)),
                        Text(
                          '₹${tool['price']}/day',
                          style: const TextStyle(
                            color: AppTheme.primaryYellow,
                            fontSize: 13,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),

                    // Rent Now Prominent Button
                    SizedBox(
                      width: double.infinity,
                      height: 32,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppTheme.primaryYellow,
                          foregroundColor: AppTheme.primaryBlack,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          padding: EdgeInsets.zero,
                          elevation: 2,
                        ),
                        onPressed: () => _navigateToBooking(tool),
                        child: const Text(
                          'Rent Now ⚡',
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 11),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _navigateToBooking(Map<String, dynamic> tool) {
    final toolModel = ToolModel(
      id: tool['name'].toString().toLowerCase().replaceAll(' ', '-'),
      name: tool['name'] as String,
      category: tool['category'] as String,
      description: 'Professional ${tool['category']} available for rent. High-quality heavy equipment maintained in excellent condition with full site safety clearance.',
      pricePerDay: (tool['price'] as num).toDouble(),
      rating: (tool['rating'] as num).toDouble(),
      reviewCount: tool['reviews'] as int,
      imageUrl: tool['image'] as String,
      imageUrls: [tool['image'] as String],
      isAvailable: tool['available'] as bool,
      vendor: VendorModel(
        id: 'vendor-${tool['name'].toString().toLowerCase().replaceAll(' ', '-')}',
        name: 'BuildRight Rentals',
        imageUrl: 'assets/images/vendor_logo.jpg',
        rating: 4.8,
        reviewCount: 180,
        location: tool['location'] as String,
        distance: 2.5,
      ),
      specifications: const [
        'Professional Grade',
        'Site Safety Certified',
        '24/7 Field Maintenance Support',
      ],
      location: tool['location'] as String,
    );
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => BookingScreen(tool: toolModel),
      ),
    );
  }
}

