import 'package:flutter/material.dart';
import '../themes/app_theme.dart';
import '../models/tool_model.dart';
import '../widgets/app_image.dart';
import 'booking_screen.dart';

class CategoriesScreen extends StatefulWidget {
  const CategoriesScreen({super.key});

  @override
  State<CategoriesScreen> createState() => _CategoriesScreenState();
}

class _CategoriesScreenState extends State<CategoriesScreen> {
  int _selectedCategory = 0;

  final List<Map<String, dynamic>> _categories = [
    {'name': 'Drilling Machines', 'icon': Icons.hardware},
    {'name': 'Concrete Mixers', 'icon': Icons.settings},
    {'name': 'Welding Machines', 'icon': Icons.bolt},
    {'name': 'Generators', 'icon': Icons.electrical_services},
    {'name': 'Ladders', 'icon': Icons.stairs},
    {'name': 'Cutting Tools', 'icon': Icons.content_cut},
    {'name': 'Safety Equipment', 'icon': Icons.security},
  ];

  List<Map<String, dynamic>> get _filteredTools {
    final categoryName = _categories[_selectedCategory]['name'];
    return _tools.where((tool) => tool['category'] == categoryName).toList();
  }

  final List<Map<String, dynamic>> _tools = [
    // Drilling Machines
    {
      'category': 'Drilling Machines',
      'name': 'Bosch Rotary Hammer Drill',
      'price': 835,
      'rating': 4.7,
      'reviews': 128,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Makita Cordless Drill',
      'price': 665,
      'rating': 4.5,
      'reviews': 89,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'DeWalt Impact Driver',
      'price': 745,
      'rating': 4.6,
      'reviews': 156,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/download.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Stanley Hammer Drill',
      'price': 575,
      'rating': 4.4,
      'reviews': 67,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Hitachi Rotary Drill',
      'price': 915,
      'rating': 4.8,
      'reviews': 142,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Black+Decker Cordless Drill',
      'price': 495,
      'rating': 4.3,
      'reviews': 78,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Milwaukee Hammer Drill',
      'price': 1085,
      'rating': 4.9,
      'reviews': 198,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Ryobi Impact Driver',
      'price': 585,
      'rating': 4.5,
      'reviews': 92,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/download.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Craftsman Drill',
      'price': 625,
      'rating': 4.4,
      'reviews': 56,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Porter Cable Drill',
      'price': 715,
      'rating': 4.6,
      'reviews': 134,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Festool Cordless Drill',
      'price': 1245,
      'rating': 4.8,
      'reviews': 167,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Metabo Hammer Drill',
      'price': 895,
      'rating': 4.7,
      'reviews': 145,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Hilti Rotary Hammer',
      'price': 1455,
      'rating': 4.9,
      'reviews': 212,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Panasonic Cordless Drill',
      'price': 675,
      'rating': 4.5,
      'reviews': 83,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/download.jpg',
      'available': false,
    },
    {
      'category': 'Drilling Machines',
      'name': 'Skil Power Drill',
      'price': 425,
      'rating': 4.3,
      'reviews': 61,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    {
      'category': 'Drilling Machines',
      'name': 'AEG Hammer Drill',
      'price': 955,
      'rating': 4.6,
      'reviews': 118,
      'location': 'Porur, Chennai',
      'image': 'assets/images/download.jpg',
      'available': true,
    },
    // Concrete Mixers
    {
      'category': 'Concrete Mixers',
      'name': 'Portable Concrete Mixer',
      'price': 1245,
      'rating': 4.8,
      'reviews': 95,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Electric Cement Mixer',
      'price': 1655,
      'rating': 4.7,
      'reviews': 72,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Diesel Concrete Mixer',
      'price': 2075,
      'rating': 4.6,
      'reviews': 54,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Mini Concrete Mixer',
      'price': 835,
      'rating': 4.5,
      'reviews': 67,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': false,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Tilting Drum Mixer',
      'price': 1455,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Reversible Mixer',
      'price': 1865,
      'rating': 4.8,
      'reviews': 112,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Pan Mixer',
      'price': 2245,
      'rating': 4.6,
      'reviews': 78,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Handheld Mixer',
      'price': 495,
      'rating': 4.4,
      'reviews': 45,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Batch Mixer',
      'price': 2875,
      'rating': 4.9,
      'reviews': 134,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Transit Mixer',
      'price': 4155,
      'rating': 4.7,
      'reviews': 67,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': false,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Self-Loading Mixer',
      'price': 5785,
      'rating': 4.8,
      'reviews': 89,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Compulsor Mixer',
      'price': 3345,
      'rating': 4.6,
      'reviews': 56,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Drum Mixer',
      'price': 1245,
      'rating': 4.5,
      'reviews': 72,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Continuous Mixer',
      'price': 2075,
      'rating': 4.7,
      'reviews': 98,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Mobile Mixer',
      'price': 1655,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Twin Shaft Mixer',
      'price': 3665,
      'rating': 4.8,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    {
      'category': 'Concrete Mixers',
      'name': 'Planetary Mixer',
      'price': 4155,
      'rating': 4.7,
      'reviews': 38,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download (1).jpg',
      'available': true,
    },
    // Welding Machines
    {
      'category': 'Welding Machines',
      'name': 'MIG Welder Pro',
      'price': 4980,
      'rating': 4.6,
      'reviews': 74,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'TIG Welding Machine',
      'price': 5815,
      'rating': 4.8,
      'reviews': 63,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Arc Welder',
      'price': 3345,
      'rating': 4.5,
      'reviews': 89,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Spot Welder',
      'price': 4155,
      'rating': 4.7,
      'reviews': 56,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': false,
    },
    {
      'category': 'Welding Machines',
      'name': 'Stick Welder',
      'price': 2875,
      'rating': 4.4,
      'reviews': 72,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Flux Core Welder',
      'price': 3665,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Plasma Cutter',
      'price': 5785,
      'rating': 4.8,
      'reviews': 134,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Oxy-Acetylene Welder',
      'price': 2475,
      'rating': 4.5,
      'reviews': 67,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Laser Welder',
      'price': 12450,
      'rating': 4.9,
      'reviews': 45,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': false,
    },
    {
      'category': 'Welding Machines',
      'name': 'Resistance Welder',
      'price': 6225,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Ultrasonic Welder',
      'price': 8665,
      'rating': 4.6,
      'reviews': 56,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Induction Welder',
      'price': 7455,
      'rating': 4.5,
      'reviews': 78,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Seam Welder',
      'price': 5365,
      'rating': 4.7,
      'reviews': 92,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Projection Welder',
      'price': 4575,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    {
      'category': 'Welding Machines',
      'name': 'Electron Beam Welder',
      'price': 16550,
      'rating': 4.8,
      'reviews': 34,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': false,
    },
    {
      'category': 'Welding Machines',
      'name': 'Friction Welder',
      'price': 9125,
      'rating': 4.6,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/welding machine.jpg',
      'available': true,
    },
    // Generators
    {
      'category': 'Generators',
      'name': 'Industrial Generator',
      'price': 6225,
      'rating': 4.5,
      'reviews': 62,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Portable Power Generator',
      'price': 4575,
      'rating': 4.7,
      'reviews': 98,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Diesel Generator',
      'price': 8665,
      'rating': 4.6,
      'reviews': 78,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Gas Generator',
      'price': 5365,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Solar Generator',
      'price': 12450,
      'rating': 4.8,
      'reviews': 134,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Inverter Generator',
      'price': 7455,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Standby Generator',
      'price': 16550,
      'rating': 4.9,
      'reviews': 67,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Prime Power Generator',
      'price': 20750,
      'rating': 4.6,
      'reviews': 45,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Silent Generator',
      'price': 9125,
      'rating': 4.7,
      'reviews': 112,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Hybrid Generator',
      'price': 14550,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Bi-Fuel Generator',
      'price': 11250,
      'rating': 4.6,
      'reviews': 78,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Natural Gas Generator',
      'price': 8665,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Propane Generator',
      'price': 7875,
      'rating': 4.7,
      'reviews': 92,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Wind Generator',
      'price': 24750,
      'rating': 4.8,
      'reviews': 34,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    {
      'category': 'Generators',
      'name': 'Hydro Generator',
      'price': 33250,
      'rating': 4.6,
      'reviews': 23,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': false,
    },
    {
      'category': 'Generators',
      'name': 'Marine Generator',
      'price': 18650,
      'rating': 4.5,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/download (2).jpg',
      'available': true,
    },
    // Ladders
    {
      'category': 'Ladders',
      'name': 'Aluminum Extension Ladder',
      'price': 1245,
      'rating': 4.6,
      'reviews': 112,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Fiberglass Step Ladder',
      'price': 905,
      'rating': 4.5,
      'reviews': 87,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Telescoping Ladder',
      'price': 1455,
      'rating': 4.7,
      'reviews': 134,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Platform Ladder',
      'price': 1655,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': false,
    },
    {
      'category': 'Ladders',
      'name': 'Attic Ladder',
      'price': 1865,
      'rating': 4.5,
      'reviews': 67,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Rolling Ladder',
      'price': 2245,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Step Stool',
      'price': 495,
      'rating': 4.4,
      'reviews': 145,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Scaffold Ladder',
      'price': 2875,
      'rating': 4.8,
      'reviews': 56,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Multi-Purpose Ladder',
      'price': 2075,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Orchard Ladder',
      'price': 1245,
      'rating': 4.5,
      'reviews': 78,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': false,
    },
    {
      'category': 'Ladders',
      'name': 'Fire Escape Ladder',
      'price': 1655,
      'rating': 4.7,
      'reviews': 92,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Pool Ladder',
      'price': 1455,
      'rating': 4.4,
      'reviews': 61,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Library Ladder',
      'price': 1865,
      'rating': 4.6,
      'reviews': 45,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Folding Ladder',
      'price': 835,
      'rating': 4.5,
      'reviews': 134,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Straight Ladder',
      'price': 745,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': true,
    },
    {
      'category': 'Ladders',
      'name': 'Articulated Ladder',
      'price': 2075,
      'rating': 4.6,
      'reviews': 67,
      'location': 'Porur, Chennai',
      'image': 'assets/images/download (3).jpg',
      'available': false,
    },
    // Cutting Tools
    {
      'category': 'Cutting Tools',
      'name': 'Angle Grinder',
      'price': 2075,
      'rating': 4.7,
      'reviews': 145,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Circular Saw',
      'price': 2475,
      'rating': 4.6,
      'reviews': 98,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Jigsaw',
      'price': 1655,
      'rating': 4.5,
      'reviews': 78,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Reciprocating Saw',
      'price': 1865,
      'rating': 4.7,
      'reviews': 112,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Table Saw',
      'price': 3345,
      'rating': 4.8,
      'reviews': 134,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Miter Saw',
      'price': 2875,
      'rating': 4.6,
      'reviews': 89,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Band Saw',
      'price': 4155,
      'rating': 4.7,
      'reviews': 67,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Chop Saw',
      'price': 2245,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Tile Saw',
      'price': 1655,
      'rating': 4.6,
      'reviews': 92,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Scroll Saw',
      'price': 2075,
      'rating': 4.7,
      'reviews': 78,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Rotary Tool',
      'price': 835,
      'rating': 4.4,
      'reviews': 145,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Oscillating Tool',
      'price': 1245,
      'rating': 4.5,
      'reviews': 112,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Router',
      'price': 1455,
      'rating': 4.6,
      'reviews': 89,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': false,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Planer',
      'price': 1865,
      'rating': 4.7,
      'reviews': 67,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Jointer',
      'price': 2245,
      'rating': 4.5,
      'reviews': 56,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    {
      'category': 'Cutting Tools',
      'name': 'Thickness Planer',
      'price': 2875,
      'rating': 4.8,
      'reviews': 45,
      'location': 'Porur, Chennai',
      'image': 'assets/images/download (4).jpg',
      'available': true,
    },
    // Safety Equipment
    {
      'category': 'Safety Equipment',
      'name': 'Safety Helmet Set',
      'price': 415,
      'rating': 4.8,
      'reviews': 234,
      'location': 'T. Nagar, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Goggles',
      'price': 250,
      'rating': 4.5,
      'reviews': 167,
      'location': 'Anna Nagar, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Gloves',
      'price': 165,
      'rating': 4.6,
      'reviews': 189,
      'location': 'Velachery, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Boots',
      'price': 835,
      'rating': 4.7,
      'reviews': 145,
      'location': 'Adyar, Chennai',
      'image': 'assets/images/images.jpg',
      'available': false,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Vest',
      'price': 295,
      'rating': 4.5,
      'reviews': 198,
      'location': 'Mylapore, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Ear Protection',
      'price': 185,
      'rating': 4.4,
      'reviews': 134,
      'location': 'Chromepet, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Face Shield',
      'price': 225,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Perambur, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Respirator Mask',
      'price': 345,
      'rating': 4.7,
      'reviews': 167,
      'location': 'Ambattur, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Harness',
      'price': 1245,
      'rating': 4.8,
      'reviews': 89,
      'location': 'Nungambakkam, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Knee Pads',
      'price': 275,
      'rating': 4.5,
      'reviews': 145,
      'location': 'Kodambakkam, Chennai',
      'image': 'assets/images/images.jpg',
      'available': false,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Safety Glasses',
      'price': 195,
      'rating': 4.6,
      'reviews': 178,
      'location': 'Ashok Nagar, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Hard Hat',
      'price': 375,
      'rating': 4.7,
      'reviews': 156,
      'location': 'Koyambedu, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'High Visibility Jacket',
      'price': 425,
      'rating': 4.5,
      'reviews': 134,
      'location': 'Guindy, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Steel Toe Shoes',
      'price': 955,
      'rating': 4.6,
      'reviews': 112,
      'location': 'Saidapet, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Dust Mask',
      'price': 85,
      'rating': 4.4,
      'reviews': 198,
      'location': 'Tiruvanmiyur, Chennai',
      'image': 'assets/images/images.jpg',
      'available': true,
    },
    {
      'category': 'Safety Equipment',
      'name': 'Welding Helmet',
      'price': 865,
      'rating': 4.7,
      'reviews': 89,
      'location': 'Porur, Chennai',
      'image': 'assets/images/images.jpg',
      'available': false,
    },
  ];

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 24, 20, 0),
            child: const Text(
              'Categories',
              style: TextStyle(
                color: AppTheme.primaryBlack,
                fontSize: 24,
                fontWeight: FontWeight.w800,
              ),
            ),
          ),
          const SizedBox(height: 20),
          // Category tabs
          SizedBox(
            height: 100,
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              scrollDirection: Axis.horizontal,
              itemCount: _categories.length,
              itemBuilder: (context, i) {
                final selected = i == _selectedCategory;
                return GestureDetector(
                  onTap: () => setState(() => _selectedCategory = i),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 200),
                    width: 88,
                    margin: const EdgeInsets.symmetric(horizontal: 4),
                    decoration: BoxDecoration(
                      color: selected
                          ? AppTheme.primaryYellow.withOpacity(0.15)
                          : AppTheme.primaryWhite,
                      borderRadius: BorderRadius.circular(14),
                      border: Border.all(
                        color: selected
                            ? AppTheme.primaryYellow
                            : AppTheme.mediumGray.withOpacity(0.3),
                        width: selected ? 1.5 : 1,
                      ),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          _categories[i]['icon'] as IconData,
                          color: selected
                              ? AppTheme.primaryYellow
                              : AppTheme.mediumGray,
                          size: 26,
                        ),
                        const SizedBox(height: 6),
                        Text(
                          _categories[i]['name'] as String,
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: selected
                                ? AppTheme.primaryYellow
                                : AppTheme.mediumGray,
                            fontSize: 10,
                            fontWeight: selected
                                ? FontWeight.w600
                                : FontWeight.w400,
                          ),
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
          const SizedBox(height: 20),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              '${_filteredTools.length} tools found',
              style: const TextStyle(color: AppTheme.mediumGray, fontSize: 13),
            ),
          ),
          const SizedBox(height: 12),
          Expanded(
            child: GridView.builder(
              padding: const EdgeInsets.fromLTRB(20, 0, 20, 24),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                crossAxisSpacing: 14,
                mainAxisSpacing: 14,
                childAspectRatio: 0.68,
              ),
              itemCount: _filteredTools.length,
              itemBuilder: (context, i) {
                final tool = _filteredTools[i];
                return _buildToolCard(tool);
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildToolCard(Map<String, dynamic> tool) {
    return GestureDetector(
      onTap: () {
        final toolModel = ToolModel(
          id: tool['name'].toString().toLowerCase().replaceAll(' ', '-'),
          name: tool['name'] as String,
          category: tool['category'] as String,
          description:
              'Professional ${tool['category']} available for rent. High-quality equipment maintained in excellent condition.',
          pricePerDay: (tool['price'] as num).toDouble(),
          rating: (tool['rating'] as num).toDouble(),
          reviewCount: tool['reviews'] as int,
          imageUrl: tool['image'] as String,
          imageUrls: [tool['image'] as String],
          isAvailable: tool['available'] as bool,
          vendor: VendorModel(
            id: 'vendor-${tool['name'].toString().toLowerCase().replaceAll(' ', '-')}',
            name: 'Tool Rental Co.',
            imageUrl: 'assets/images/download.jpg',
            rating: 4.5,
            reviewCount: 120,
            location: tool['location'] as String,
            distance: 2.5,
          ),
          specifications: const [
            'Professional Grade',
            'Well Maintained',
            'Easy to Use',
            'Safety Certified',
          ],
          location: tool['location'] as String,
        );
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => BookingScreen(tool: toolModel),
          ),
        );
      },
      child: Container(
        decoration: BoxDecoration(
          color: AppTheme.primaryWhite,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: AppTheme.mediumGray.withOpacity(0.3)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Image + badges
            Stack(
              children: [
                ClipRRect(
                  borderRadius: const BorderRadius.vertical(
                    top: Radius.circular(16),
                  ),
                  child: AspectRatio(
                    aspectRatio: 1.1,
                    child: AppImage(
                      imageUrl: tool['image'] as String,
                    ),
                  ),
                ),
                if (!(tool['available'] as bool))
                  Positioned(
                    top: 8,
                    left: 8,
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: BoxDecoration(
                        color: AppTheme.accentRed,
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: const Text(
                        'Unavailable',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 10,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                Positioned(
                  top: 8,
                  right: 8,
                  child: Container(
                    width: 32,
                    height: 32,
                    decoration: const BoxDecoration(
                      color: Colors.white,
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.favorite_border,
                      color: AppTheme.accentRed,
                      size: 16,
                    ),
                  ),
                ),
              ],
            ),
            // Text content
            Padding(
              padding: const EdgeInsets.all(10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    tool['name'] as String,
                    style: const TextStyle(
                      color: AppTheme.primaryBlack,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      const Icon(
                        Icons.star_rounded,
                        color: AppTheme.primaryYellow,
                        size: 14,
                      ),
                      const SizedBox(width: 3),
                      Text(
                        '${tool['rating']} (${tool['reviews']})',
                        style: const TextStyle(
                          color: AppTheme.mediumGray,
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 6),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        '₹${tool['price']}/day',
                        style: const TextStyle(
                          color: AppTheme.primaryYellow,
                          fontSize: 14,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      Row(
                        children: [
                          const Icon(
                            Icons.location_on_outlined,
                            color: AppTheme.mediumGray,
                            size: 11,
                          ),
                          Text(
                            tool['location'] as String,
                            style: const TextStyle(
                              color: AppTheme.mediumGray,
                              fontSize: 10,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
